# Generated by Django 4.2.2 on 2023-06-13 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_department_ct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='ct',
        ),
        migrations.AddField(
            model_name='department',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='department',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
