# Generated by Django 4.2.1 on 2023-07-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_alter_department_add_date_alter_department_mod_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级'), (4, '四级'), (5, '五级')], default=1, verbose_name='手机等级')),
                ('status', models.SmallIntegerField(choices=[(1, '未启用'), (2, '已使用')], default=1, verbose_name='手机号使用状态')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='depart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.department', verbose_name='部门'),
        ),
    ]
