# Generated by Django 4.2.1 on 2023-07-05 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_prettynum_alter_employee_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='prettynum',
            name='create_date',
            field=models.DateTimeField(auto_created=True, default=datetime.date(2023, 7, 6), verbose_name='创建时间'),
        ),
    ]
