# Generated by Django 4.2.1 on 2023-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='age',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userlist',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
